version: "3.6"

services:
  shell:
    build:
      context: ./shell
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
  content:
    build:
      context: ./content
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
  svelte-content:
    build:
      context: ./svelte-content
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
